Asm2_1670/Models/Job.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;

namespace Asm2_1670.Models
{
	public class Job
	{
		public int Id { get; set; }
		public string UserId { get; set; }
		[ForeignKey("UserId")]
		public User? User { get; set; }
		public string JobTitle { get; set; }
		public string Description { get; set; }
		public string Email { get; set; }
		public string Name { get; set; }
		public string JobType { get; set; }
		[ValidateNever]
		public int CategoriesId { get; set; }
		[ForeignKey("CategoriesId")]
		[ValidateNever]
		public Categories Categories { get; set; }
		public string OfferdSalary { get; set; }
		public string CareerLevel { get; set; }
		public string Experience { get; set; }
		public string Gender { get; set; }
		public string EndDay { get; set; }
		public string Qualification { get; set; }
		public string Country { get; set; }
		public string City { get; set; }
		public int? Count { get; set; }
	}
}

Asm2_1670/Areas/Employer/Controllers/ApplicationController.cs
using Asm2_1670.Models;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace Asm2_1670.Areas.Employer.Controllers
{
	[Area("Employer")]
	[Authorize(Roles = "Employer")]
	public class ApplicationController : Controller
	{
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IUnitOfWork _unitOfWork;
		public ApplicationController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}
		public string TakeIdUser()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			return userId;
		}
		public Asm2_1670.Models.User TakeUser(string userId)
		{
			Asm2_1670.Models.User? user = _unitOfWork.UsersRepository.Get(u => u.Id == userId);

			ViewBag.UserId = userId;
			ViewBag.Email = user.Email;
			ViewBag.Name = user.Name;
			return user;
		}
		public IActionResult ViewApplication(int? id)
		{
			ViewBag.JobId = id;
			List<Application> listApplication = _unitOfWork.ApplicationsRepository.GetAll().Where(a => a.JobId == id).ToList();
			List<Asm2_1670.Models.User> listUser = new List<Models.User>();
			foreach(var apply in listApplication)
			{
				if (apply.Status == "Processing")
				{
					listUser.Add(_unitOfWork.UsersRepository.Get(u => u.Id == apply.UserId));
				}
			}
			return View(listUser);
		}
		public IActionResult Rejected(int? id, string? data)
		{
			Application apply = _unitOfWork.ApplicationsRepository.Get(a => a.JobId == id && a.UserId == data);
			apply.Status = "Rejected";
			_unitOfWork.ApplicationsRepository.Update(apply);
			_unitOfWork.Save();

            return RedirectToAction("ViewApplication");
        }
        public IActionResult Approved(int? id, string? data)
        {
            Application apply = _unitOfWork.ApplicationsRepository.Get(a => a.JobId == id && a.UserId == data);
            apply.Status = "Approved";
            _unitOfWork.ApplicationsRepository.Update(apply);
            _unitOfWork.Save();

            return RedirectToAction("ViewApplication",id);
        }
    }
}

Asm2_1670/Areas/Employer/Controllers/JobController.cs
using Asm2_1670.Models;
using Asm2_1670.Models.ViewModels;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace Asm2_1670.Areas.Employer.Controllers
{
	[Area("Employer")]
	[Authorize(Roles = "Employer")]
	public class JobController : Controller
	{
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IUnitOfWork _unitOfWork;
		public JobController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}
		public string TakeIdUser()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			return userId;
		}
		public Asm2_1670.Models.User TakeUser(string userId)
		{
			Asm2_1670.Models.User? user = _unitOfWork.UsersRepository.Get(u => u.Id == userId);

			ViewBag.UserId = userId;
			ViewBag.Email = user.Email;
			ViewBag.Name = user.Name;
			return user;
		}
		public IActionResult Postnew()
		{
			string userId = TakeIdUser();
			TakeUser(userId);
			JobVM jobVM = new JobVM()
			{
				Categories = _unitOfWork.CategoriesRepository.GetAll().Where(c => c.Status == "Active").Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				}),
				Job = new Job()
			};
			return View(jobVM);
		}
		[HttpPost]
		public IActionResult Postnew(JobVM jobVM)
		{
			string userId = TakeIdUser();
			TakeUser(userId);
			if (jobVM != null)
			{
				jobVM.Job.Email = ViewBag.Email;
				jobVM.Job.Name = ViewBag.Name;
				_unitOfWork.JobsRepository.Add(jobVM.Job);
				_unitOfWork.Save();
				return RedirectToAction("ManagerJob");
			}
			jobVM.Categories = _unitOfWork.CategoriesRepository.GetAll().Where(c => c.Status == "Active").Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString(),
			});
			return View(jobVM);
		}
		public IActionResult ManagerJob()
		{
			int count;
			string userId = TakeIdUser();
			TakeUser(userId);
			if (userId == null)
			{
				return NotFound();
			}
			List<Job> mylist = _unitOfWork.JobsRepository.GetAll().Where(j => j.UserId == userId).ToList();
			foreach(var job in mylist)
			{
				count = _unitOfWork.ApplicationsRepository.GetAll().Count(a => a.JobId == job.Id && a.Status == "Processing");
				job.Count = count;
			}
			return View(mylist);
		}
		public IActionResult EditJob(int? id)
		{
			string userId = TakeIdUser();
			TakeUser(userId);
			JobVM jobVM = new JobVM()
			{
				Categories = _unitOfWork.CategoriesRepository.GetAll().Where(c => c.Status == "Active").Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				}),
				Job = _unitOfWork.JobsRepository.Get(j => j.Id == id)
			};
			jobVM.Categories = _unitOfWork.CategoriesRepository.GetAll().Where(c => c.Status == "Active").Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString(),
			});
			return View(jobVM);
		}
		[HttpPost]
		public IActionResult EditJob(JobVM jobVM)
		{
			if (ModelState.IsValid)
			{
				_unitOfWork.JobsRepository.Update(jobVM.Job);
				_unitOfWork.Save();
				return RedirectToAction("ManagerJob");
			}
			jobVM.Categories = _unitOfWork.CategoriesRepository.GetAll().Where(c => c.Status == "Active").Select(c => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString(),
			});
			return View(jobVM);
		}
		public IActionResult DeleteJob(int? id)
		{
			Job? job = _unitOfWork.JobsRepository.Get(j => j.Id == id, "Categories");
			return View(job);
		}
		[HttpPost]
		public IActionResult DeleteJob(Job job)
		{
			_unitOfWork.JobsRepository.Delete(job);
			_unitOfWork.Save();
			return RedirectToAction("ManagerJob");
		}
	}
}

Asm2_1670/Areas/User/Controllers/JobController.cs
using Asm2_1670.Models;
using Asm2_1670.Models.ViewModels;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Asm2_1670.Areas.User.Controllers
{
    [Area("User")]
    public class JobController : Controller
    {
		private readonly IUnitOfWork _unitOfWork;
		public JobController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public string TakeIdUser()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			return userId;
		}
		public Asm2_1670.Models.User TakeUser(string userId)
		{
			Asm2_1670.Models.User? user = _unitOfWork.UsersRepository.Get(u => u.Id == userId);

			ViewBag.UserId = userId;
			ViewBag.Email = user.Email;
			ViewBag.Name = user.Name;
			ViewBag.Image = user.ImageUrl;
			return user;
		}
		public IActionResult Index()
        {
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToAction("Login", "Account", new { area = "Identity" });
			}
			if (User.Identity.IsAuthenticated)
			{
				string UserId = TakeIdUser();
				TakeUser(UserId);
			}
			JobAppVM jobAppVM = new JobAppVM()
			{
				Application = new Application(),
				MyListJob = _unitOfWork.JobsRepository.GetAll().ToList(),
				MyListApplication = _unitOfWork.ApplicationsRepository.GetAll().ToList()
			};
			foreach(var job in jobAppVM.MyListJob)
			{
				job.User = _unitOfWork.UsersRepository.Get(u => u.Id == job.UserId);
			}
			return View(jobAppVM);

		}
		
        public IActionResult Jobdetail(int? id)
        {
			Asm2_1670.Models.User user = TakeUser(TakeIdUser());
			if (id == null || id == 0)
			{
				return NotFound();
			}
			JobAppVM JobAppVM = new JobAppVM()
			{
				Job = _unitOfWork.JobsRepository.Get(j => j.Id == id),
				Application = new Application(),
				MyListApplication = _unitOfWork.ApplicationsRepository.GetAll().ToList()
			};
			JobAppVM.Job.User = _unitOfWork.UsersRepository.Get(u => u.Id == JobAppVM.Job.UserId);
			return View(JobAppVM);
        }
    }
}

Asm2_1670/Areas/Employer/Views/Job/DeleteJob.cshtml
@model Job
<body>
<div class="theme-layout" id="scrollup">
	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url(images/mslider1.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Welcome Tera Planer</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section>
		<div class="block no-padding">
			<div class="container">
				 <div class="row no-gape">
					 <aside class="col-lg-3 column border-right">
						 <div class="widget">
							 <div class="tree_widget-sec">
								 <ul>
									 <li><a href="employer_profile.html" title=""><i class="la la-file-text"></i>Company Profile</a></li>
									 <li><a href="employer_manage_jobs.html" title=""><i class="la la-briefcase"></i>Manage Jobs</a></li>
									 <li><a href="employer_transactions.html" title=""><i class="la la-money"></i>Transactions</a></li>
									 <li><a href="employer_resume.html" title=""><i class="la la-paper-plane"></i>Resumes</a></li>
									 <li><a href="employer_packages.html" title=""><i class="la la-user"></i>Packages</a></li>
									 <li><a title=""><i class="la la-file-text"></i>Post a New Job</a></li>
									 <li><a href="employer_job_alert.html" title=""><i class="la la-flash"></i>Job Alerts</a></li>
									 <li><a href="employer_change_password.html" title=""><i class="la la-lock"></i>Change Password</a></li>
									 <li><a href="#" title=""><i class="la la-unlink"></i>Logout</a></li>
								 </ul>
							 </div>
						 </div>
					 </aside>
					 <div class="col-lg-9 column">
						 <div class="padding-left">
							 <div class="profile-title">
								 <h3>Delete Job</h3>
							 </div>
							 <div class="profile-form-edit">
								 <form method="post">
									 <div class="row">
										<input hidden asp-for="Id"/> 
										 <input hidden asp-for="UserId"/>
										 <span asp-validation-for="UserId" class="text-danger"></span>
										 <div class="col-lg-12">
											 <span class="pf-title">Job Title</span>
											 <div class="pf-field">
												 <input disabled asp-for="JobTitle" type="text" placeholder="Designer">
												 <span asp-validation-for="JobTitle" class="text-danger"></span>
											 </div>
										 </div>
										 <div class="col-lg-12">
											 <span class="pf-title">Description</span>
											 <div class="pf-field">
												 <textarea disabled asp-for="Description">Spent several years working on sheep on Wall Street. Had moderate success investing in Yugos on Wall Street. Managed a small team buying and selling pogo sticks for farmers. Spent several years licensing licorice in West Palm Beach, FL. Developed severalnew methods for working with banjos in the aftermarket. Spent a weekend importing banjos in West Palm Beach, FL.In this position, the Software Engineer ollaborates with Evention's Development team to continuously enhance our current software solutions as well as create new solutions to eliminate the back-office operations and management challenges present</textarea>
												 <span asp-validation-for="Description" class="text-danger"></span>
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Email</span>
											 <div class="pf-field">
												 <input hidden disabled asp-for="Email" type="text" value="@ViewBag.Email">
												 <span asp-validation-for="Email" class="text-danger"></span>
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Company Name</span>
											 <div class="pf-field">
												 <input hidden disabled asp-for="Name" type="text" value="@ViewBag.Name">
												 <span asp-validation-for="Name" class="text-danger"></span>
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Job Type</span>
											 <div class="pf-field">
												 <input disabled asp-for="JobType" type="text" placeholder="Designer">
												<span asp-validation-for="JobType" class="text-danger"></span>
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Categories</span>
											 <div class="pf-field">
												 <input disabled asp-for="Categories.Name" type="text" placeholder="Designer">
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Offerd Salary</span>
											 <div class="pf-field">
												 <input disabled asp-for="OfferdSalary" type="text" placeholder="Designer">
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Career Level</span>
											 <div class="pf-field">
												 <input disabled asp-for="CareerLevel" type="text" placeholder="Designer">
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Experience</span>
											 <div class="pf-field">
												  <input disabled asp-for="Experience" type="text" placeholder="Designer">
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Gender</span>
											 <div class="pf-field">
												 <input disabled asp-for="Gender" type="text" placeholder="Designer">
												
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Application Deadline Date</span>
											 <div class="pf-field">
												 <input disabled asp-for="EndDay" type="text" placeholder="01.11.207" class="form-control datepicker">
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Qualification</span>
											 <div class="pf-field">
												 <input disabled asp-for="Qualification" type="text" placeholder="Designer">
												
											 </div>
										 </div>
										 <div class="col-lg-6">
											 <span class="pf-title">Country</span>
											 <div class="pf-field">
												 <input disabled asp-for="Country" type="text"/>
											 </div>
										 </div>
										 <div class="col-lg-6" style="margin-bottom: 200px">
											 <span class="pf-title">City</span>
											 <div class="pf-field">
												 <input disabled asp-for="City" type="text"/>
											 </div>
										 </div>
										 <div class="col-lg-12">
											<button type="submit">Delete</button>
											</div>
									 </div>
								 </form>
							 </div>
						 </div>
					</div>
				 </div>
			</div>

		</div>
	</section>
	</div>

<!-- Include Date Range Picker -->
<link rel="stylesheet" type="text/css" href="css/bootstrap-datepicker.css">
<script src="~/js/bootstrap-datepicker.js" type="text/javascript"></script>
<script>
		$(function(){
			$('.datepicker').datepicker({
				format: 'mm-dd-yyyy'
			});
		});
</script>
</body>

Asm2_1670/Areas/Employer/Views/Job/ManagerJob.cshtml
@using Microsoft.AspNetCore.Identity
@model List<Job>

<body>
<div class="theme-layout" id="scrollup">
	<section class="overlape">
		<div class="block no-padding">
			<div data-velocity="-.1" style="background: url(images/mslider1.jpg) repeat scroll 50% 422.28px transparent;" class="parallax scrolly-invisible no-parallax"></div><!-- PARALLAX BACKGROUND IMAGE -->
			<div class="container fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="inner-header">
							<h3>Welcome @ViewBag.Name</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="block no-padding">
			<div class="container">
				 <div class="row no-gape">
					 <aside class="col-lg-3 column border-right">
						 <div class="widget">
							 <div class="tree_widget-sec">
								 <ul>
									 <li><a href="employer_profile.html" title=""><i class="la la-file-text"></i>Company Profile</a></li>
									 <li><a href="employer_manage_jobs.html" title=""><i class="la la-briefcase"></i>Manage Jobs</a></li>
									 <li><a href="employer_transactions.html" title=""><i class="la la-money"></i>Transactions</a></li>
									 <li><a href="employer_resume.html" title=""><i class="la la-paper-plane"></i>Resumes</a></li>
									 <li><a href="employer_packages.html" title=""><i class="la la-user"></i>Packages</a></li>
									 <li><a href="employer_post_new.html" title=""><i class="la la-file-text"></i>Post a New Job</a></li>
									 <li><a href="employer_job_alert.html" title=""><i class="la la-flash"></i>Job Alerts</a></li>
									 <li><a href="employer_change_password.html" title=""><i class="la la-lock"></i>Change Password</a></li>
									 <li><a href="#" title=""><i class="la la-unlink"></i>Logout</a></li>
								 </ul>
							 </div>
						 </div>
					 </aside>
					 <div class="col-lg-9 column">
						 <div class="padding-left">
							 <div class="manage-jobs-sec">
								 <h3>Manage Jobs</h3>
								 <div class="extra-job-info">
									 <span><i class="la la-clock-o"></i><strong>9</strong> Job Posted</span>
									 <span><i class="la la-file-text"></i><strong>20</strong> Application</span>
									 <span><i class="la la-users"></i><strong>18</strong> Active Jobs</span>
								 </div>
								 <table>
									 <thead>
										 <tr>
											 <td>Title</td>
											 <td>Applications</td>
											 <td>Deadline</td>
											 <td>Action</td>
										 </tr>
									 </thead>
									 <tbody>
										 @foreach (var job in Model){
												<tr>
													 <td>
														 <div class="table-list-title">
															 <h3><a href="#" title="">@job.JobTitle</a></h3>
															 <span><i class="la la-map-marker"></i>@job.City, @job.Country</span>
														 </div>
													 </td>
													 <td>
														 <span class="applied-field">@job.Count Applied</span>
													 </td>
													 <td>
														 <span>@job.EndDay</span>
													 </td>
													 <td>
														 <ul class="action_job">
															 <li><span>View Applications</span><a asp-controller="Application" asp-action="ViewApplication" asp-route-id="@job.Id"><i class="la la-eye"></i></a></li>
															 <li><span>Edit</span><a asp-controller="Job" asp-action="EditJob" asp-route-id="@job.Id"><i class="la la-pencil"></i></a></li>
															 <li><span>Delete</span><a asp-controller="Job" asp-action="DeleteJob" asp-route-id="@job.Id"><i class="la la-trash-o"></i></a></li>
														 </ul>
													 </td>
												</tr>
										  }
									 </tbody>
								 </table>
								 <div class="col-lg-12">
									<button><a asp-controller="Job" asp-action="Postnew">Post New Job</a></button>
								 </div>
							 </div>
						 </div>
					</div>
				 </div>
			</div>
		</div>
	</section>
</div>

</body>