Asm2_1670/Areas/Admin/Controllers/CategoriesController.cs
using Asm2_1670.Data;
using Asm2_1670.Models;
using Asm2_1670.Repository;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Asm2_1670.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class CategoriesController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public CategoriesController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public IActionResult Index()
		{
			List<Categories> myList = _unitOfWork.CategoriesRepository.GetAll().ToList();
			return View(myList);
		}
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Categories categories)
		{
			if(ModelState.IsValid)
			{
				_unitOfWork.CategoriesRepository.Add(categories);
				_unitOfWork.Save();
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Edit(int? id)
		{
			if(id == null || id == 0)
			{
				return NotFound();
			}
			Categories? category = _unitOfWork.CategoriesRepository.Get(c => c.Id == id);
			if(category == null)
			{
				return NotFound();
			}
			return View(category);
		}
		[HttpPost]
		public IActionResult Edit(Categories category)
		{
			if (ModelState.IsValid)
			{
				_unitOfWork.CategoriesRepository.Update(category);
				_unitOfWork.Save();
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			Categories? category = _unitOfWork.CategoriesRepository.Get(c => c.Id == id);
			if (category == null)
			{
				return NotFound();
			}
			return View(category);
		}
		[HttpPost]
		public IActionResult Delete(Categories category)
		{
			_unitOfWork.CategoriesRepository.Delete(category);
			_unitOfWork.Save();
			return RedirectToAction("Index");
		}
	}
	
}

Asm2_1670/Areas/Candidate/Controllers/ApplyController.cs
using Asm2_1670.Models;
using Asm2_1670.Models.ViewModels;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Security.Claims;

namespace Asm2_1670.Areas.Candidate.Controllers
{
	[Area("Candidate")]
	[Authorize(Roles = "Candidate")]
	public class ApplyController : Controller
	{
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IUnitOfWork _unitOfWork;
		public ApplyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}
		public string TakeIdUser()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			return userId;
		}
		public Asm2_1670.Models.User TakeUser(string userId)
		{
			Asm2_1670.Models.User? user = _unitOfWork.UsersRepository.Get(u => u.Id == userId);

			ViewBag.UserId = userId;
			ViewBag.Email = user.Email;
			ViewBag.Name = user.Name;
			return user;
		}
		public IActionResult Index()
		{
			string userId = TakeIdUser();
			List<Application> listApply = _unitOfWork.ApplicationsRepository.GetAll().Where(Application => Application.UserId == userId).ToList();
			foreach(var obj in listApply)
			{
				var job = _unitOfWork.JobsRepository.Get(j => j.Id == obj.JobId);
				obj.Job = job;
			}
			return View(listApply);
		}
		public IActionResult ApplyJob(int? id, string? data)
		{
			string currentTime = DateTime.Now.ToShortDateString();
			Application application = new Application
			{
				JobId = (int)id,
				UserId = data,
				AppliedTime = currentTime,
				Status = "Processing"
			};
			_unitOfWork.ApplicationsRepository.Add(application);
			_unitOfWork.Save();
			
			return RedirectToAction("Index", "Job", new { area = "User" });
		}
		public IActionResult Delete(int? id)
		{
			if(id == null || id == 0)
			{
				return NotFound();
			}
			Application? apply = _unitOfWork.ApplicationsRepository.Get(a => a.Id == id);
			_unitOfWork.ApplicationsRepository.Delete(apply);
			_unitOfWork.Save();
			return RedirectToAction("Index");
		}
	}
}

Asm2_1670/Areas/User/Controllers/JobController.cs
using Asm2_1670.Models;
using Asm2_1670.Models.ViewModels;
using Asm2_1670.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Asm2_1670.Areas.User.Controllers
{
    [Area("User")]
    public class JobController : Controller
    {
		private readonly IUnitOfWork _unitOfWork;
		public JobController(IUnitOfWork unitOfWork)
		{
			_unitOfWork = unitOfWork;
		}
		public string TakeIdUser()
		{
			var claimIdentity = (ClaimsIdentity)User.Identity;
			string userId = claimIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			return userId;
		}
		public Asm2_1670.Models.User TakeUser(string userId)
		{
			Asm2_1670.Models.User? user = _unitOfWork.UsersRepository.Get(u => u.Id == userId);

			ViewBag.UserId = userId;
			ViewBag.Email = user.Email;
			ViewBag.Name = user.Name;
			ViewBag.Image = user.ImageUrl;
			return user;
		}
		public IActionResult Index()
        {
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToAction("Login", "Account", new { area = "Identity" });
			}
			if (User.Identity.IsAuthenticated)
			{
				string UserId = TakeIdUser();
				TakeUser(UserId);
			}
			JobAppVM jobAppVM = new JobAppVM()
			{
				Application = new Application(),
				MyListJob = _unitOfWork.JobsRepository.GetAll().ToList(),
				MyListApplication = _unitOfWork.ApplicationsRepository.GetAll().ToList()
			};
			foreach(var job in jobAppVM.MyListJob)
			{
				job.User = _unitOfWork.UsersRepository.Get(u => u.Id == job.UserId);
			}
			return View(jobAppVM);

		}
		
        public IActionResult Jobdetail(int? id)
        {
			Asm2_1670.Models.User user = TakeUser(TakeIdUser());
			if (id == null || id == 0)
			{
				return NotFound();
			}
			JobAppVM JobAppVM = new JobAppVM()
			{
				Job = _unitOfWork.JobsRepository.Get(j => j.Id == id),
				Application = new Application(),
				MyListApplication = _unitOfWork.ApplicationsRepository.GetAll().ToList()
			};
			JobAppVM.Job.User = _unitOfWork.UsersRepository.Get(u => u.Id == JobAppVM.Job.UserId);
			return View(JobAppVM);
        }
    }
}

Asm2_1670/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<Asm2_1670.Models.User> SignInManager
@inject UserManager<Asm2_1670.Models.User> UserManager
<!DOCTYPE html><html><head>

	<title>Job Hunt</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="CreativeLayers">

	<!-- Styles -->
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/AppDevGCD1104.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>

	<link rel="stylesheet" type="text/css" href="~/css/bootstrap-grid.css">
	<link rel="stylesheet" href="~/css/icons.css">
	<link rel="stylesheet" href="~/css/animate.min.css">
	<link rel="stylesheet" type="text/css" href="~/css/style.css">
	<link rel="stylesheet" type="text/css" href="~/css/responsive.css">
	<link rel="stylesheet" type="text/css" href="~/css/chosen.css">
	<link rel="stylesheet" type="text/css" href="~/css/colors.css">
	<link rel="stylesheet" type="text/css" href="~/css/bootstrap.css">
	<link rel="stylesheet" href="~/css/font-awesome.min.css">

</head>
<body>
<div class="page-loading">
	<img src="~/images/loader.gif" alt="">
</div>
<div class="theme-layout" id="scrollup">
			<div class="responsive-header">
				<div class="responsive-menubar">
					<div class="res-logo"><a href="index.html" title=""><img src="~/images/logo.png" alt=""></a></div>
					<div class="menu-resaction">
						<div class="res-openmenu">
							<img src="~/images/icon.png" alt=""> Menu
						</div>
						<div class="res-closemenu">
							<img src="~/images/icon2.png" alt=""> Close
						</div>
					</div>
				</div>
				<div class="responsive-opensec">
					<div class="btn-extars">
						@if (User.IsInRole("Employer"))
						{
							<a asp-area="Employer" asp-controller="Employer" asp-action="Postnew" class="post-job-btn"><i class="la la-plus"></i>Post Jobs</a>
						}
						<partial name="_LoginPartial" />
					</div><!-- Btn Extras -->
					<form class="res-search">
						<input type="text" placeholder="Job title, keywords or company name">
						<button type="submit"><i class="la la-search"></i></button>
					</form>
					<div class="responsivemenu">
						<ul>
							<li class="menu-item-has-children">
								<a asp-area="User" asp-controller="Home" asp-action="Index">Home</a>
							</li>
							@if ((User.IsInRole("Employer")))
							{
								<li class="menu-item-has-children">
									<a href="#" title="">Employer</a>
									<ul>
										<li><a asp-area="Employer" asp-controller="Job" asp-action="ManagerJob">Employer Job Manager</a></li>
										<li><a asp-area="Employer" asp-controller="Job" asp-action="Postnew">Employer Post New</a></li>
										<li><a asp-area="Employer" asp-controller="Categories" asp-action="Index">Request Category</a></li>
									</ul>
								</li>
							}
							@if (User.IsInRole("Candidate"))
							{
								<li class="menu-item-has-children">
									<a href="#" title="">Candidates</a>
									<ul>
										<li><a asp-area="Candidate" asp-controller="Profile" asp-action="Resume">Candidates Resume</a></li>
										<li><a asp-area="Candidate" asp-controller="Profile" asp-action="Profile" asp-route-data="@UserManager.GetUserId(User)">Candidates Profile</a></li>
										<li><a href="candidates_single.html" title="">Candidates Shortlist</a></li>
										<li><a asp-area="Candidate" asp-controller="Apply" asp-action="Index">Applied Jobs</a></li>
									</ul>
								</li>
							}
							@if (User.IsInRole("Admin"))
							{
									<li class="menu-item-has-children">
											<a href="#" title="">Admin</a>
										<ul>
											<li><a asp-area="Admin" asp-controller="Categories" asp-action="Index">Manager Categories</a></li>
											<li><a asp-area="Admin" asp-controller="Account" asp-action="Index">Manager Account</a></li>
										</ul>
									</li>
							}
							<li class="menu-item-has-children">
								<a asp-area="User" asp-controller="Job" asp-action="Index">Job</a>
							</li>
							<li class="menu-item-has-children">
								<a href="#" title="">Pages</a>
								<ul>
									<li><a href="about.html" title="">About Us</a></li>
									<li><a href="404.html" title="">404 Error</a></li>
									<li><a href="contact.html" title="">Contact Us</a></li>
									<li><a href="faq.html" title="">FAQ's</a></li>
									<li><a href="how_it_works.html" title="">How it works</a></li>
									<li><a href="login.html" title="">Login</a></li>
									<li><a href="pricing.html" title="">Pricing Plans</a></li>
									<li><a href="register.html" title="">Register</a></li>
									<li><a href="terms_and_condition.html" title="">Terms &amp; Condition</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>

			<header class="stick-top forsticky">
				<div class="menu-sec">
					<div class="container">
						<div class="logo">
							<a href="index.html" title=""><img class="hidesticky" src="~/images/logo.png" alt=""><img class="showsticky" src="~/images/logo10.png" alt=""></a>
						</div><!-- Logo -->
						<div class="btn-extars">
							@if (User.IsInRole("Employer"))
							{
								<a asp-area="Employer" asp-controller="Job" asp-action="Postnew" class="post-job-btn"><i class="la la-plus"></i>Post Jobs</a>
							}
							<partial name="_LoginPartial" />
						</div><!-- Btn Extras -->
						<nav>
							<ul>
								<li class="menu-item-has-children">
									<a asp-area="User" asp-controller="Home" asp-action="Index">Home</a>
								</li>
								@if (User.IsInRole("Employer"))
								{
									<li class="menu-item-has-children">
										<a href="#" title="">Employer</a>
										<ul>
											<li><a asp-area="Employer" asp-controller="Job" asp-action="ManagerJob">Employer Job Manager</a></li>
											<li><a asp-area="Employer" asp-controller="Job" asp-action="Postnew">Employer Post New</a></li>
											<li><a asp-area="Employer" asp-controller="Categories" asp-action="Index">Request Category</a></li>
										</ul>
									</li>
								}
								@if (User.IsInRole("Candidate"))
								{
									<li class="menu-item-has-children">
										<a href="#" title="">Candidates</a>
										<ul>
											<li><a asp-area="Candidate" asp-controller="Profile" asp-action="Resume">Candidates Resume</a></li>
											<li><a asp-area="Candidate" asp-controller="Profile" asp-action="Profile" asp-route-data="@UserManager.GetUserId(User)">Candidates Profile</a></li>
											<li><a href="candidates_single.html" title="">Candidates Shortlist</a></li>
											<li><a asp-area="Candidate" asp-controller="Apply" asp-action="Index">Applied Jobs</a></li>
										</ul>
									</li>
								}
								@if (User.IsInRole("Admin"))
								{
										<li class="menu-item-has-children">
												<a href="#" title="">Admin</a>
											<ul>
												<li><a asp-area="Admin" asp-controller="Categories" asp-action="Index">Manager Categories</a></li>
												<li><a asp-area="Admin" asp-controller="Account" asp-action="Index">Manager Account</a></li>
											</ul>
										</li>
								}
								<li class="menu-item-has-children">
									<a asp-area="User" asp-controller="Job" asp-action="Index">Job</a>
								</li>
								<li class="menu-item-has-children">
									<a href="#" title="">Pages</a>
									<ul>
										<li><a href="about.html" title="">About Us</a></li>
										<li><a href="404.html" title="">404 Error</a></li>
										<li><a href="contact.html" title="">Contact Us</a></li>
										<li><a href="faq.html" title="">FAQ's</a></li>
										<li><a href="how_it_works.html" title="">How it works</a></li>
										<li><a href="login.html" title="">Login</a></li>
										<li><a href="pricing.html" title="">Pricing Plans</a></li>
										<li><a href="register.html" title="">Register</a></li>
										<li><a href="terms_and_condition.html" title="">Terms &amp; Condition</a></li>
									</ul>
								</li>
							</ul>
						</nav><!-- Menus -->
					</div>
				</div>
			</header>
		<div>
		</div>
		<main>
			@RenderBody()
		</main>
	</div>

		<footer style="margin-top: 200px">
		<div class="block">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 column">
						<div class="widget">
							<div class="about_widget">
								<div class="logo">
									<a href="index.html" title=""><img src="~/images/logo.png" alt=""></a>
								</div>
								<span>Collin Street West, Victor 8007, Australia.</span>
								<span>+1 246-345-0695</span>
								<span>info@jobhunt.com</span>
								<div class="social">
									<a href="#" title=""><i class="fa fa-facebook"></i></a>
									<a href="#" title=""><i class="fa fa-twitter"></i></a>
									<a href="#" title=""><i class="fa fa-linkedin"></i></a>
									<a href="#" title=""><i class="fa fa-pinterest"></i></a>
									<a href="#" title=""><i class="fa fa-behance"></i></a>
								</div>
							</div><!-- About Widget -->
						</div>
					</div>
					<div class="col-lg-4 column">
						<div class="widget">
							<h3 class="footer-title">Frequently Asked Questions</h3>
							<div class="link_widgets">
								<div class="row">
									<div class="col-lg-6">
										<a href="#" title="">Privacy &amp; Seurty </a>
										<a href="#" title="">Terms of Serice</a>
										<a href="#" title="">Communications </a>
										<a href="#" title="">Referral Terms </a>
										<a href="#" title="">Lending Licnses </a>
										<a href="#" title="">Disclaimers </a>	
									</div>
									<div class="col-lg-6">
										<a href="#" title="">Support </a>
										<a href="#" title="">How It Works </a>
										<a href="#" title="">For Employers </a>
										<a href="#" title="">Underwriting </a>
										<a href="#" title="">Contact Us</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-2 column">
						<div class="widget">
							<h3 class="footer-title">Find Jobs</h3>
							<div class="link_widgets">
								<div class="row">
									<div class="col-lg-12">
										<a href="#" title="">US Jobs</a>	
										<a href="#" title="">Canada Jobs</a>	
										<a href="#" title="">UK Jobs</a>	
										<a href="#" title="">Emplois en Fnce</a>	
										<a href="#" title="">Jobs in Deuts</a>	
										<a href="#" title="">Vacatures China</a>	
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3 column">
						<div class="widget">
							<div class="download_widget">
								<a href="#" title=""><img src="~/images/dw1.png" alt=""></a>
								<a href="#" title=""><img src="~/images/dw2.png" alt=""></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="bottom-line">
			<span>© 2018 Jobhunt All rights reserved. Design by Creative Layers</span>
			<a href="#scrollup" class="scrollup" title=""><i class="la la-arrow-up"></i></a>
		</div>
	</footer>
<script src="~/js/jquery.min.js" type="text/javascript"></script>
<script src="~/js/modernizr.js" type="text/javascript"></script>
<script src="~/js/script.js" type="text/javascript"></script>
<script src="~/js/bootstrap.min.js" type="text/javascript"></script>
<script src="~/js/wow.min.js" type="text/javascript"></script>
<script src="~/js/slick.min.js" type="text/javascript"></script>
<script src="~/js/parallax.js" type="text/javascript"></script>
<script src="~/js/select-chosen.js" type="text/javascript"></script>
<script src="~/js/jquery.scrollbar.min.js" type="text/javascript"></script>
<script src="~/js/tag.js" type="text/javascript"></script>
<script src="~/js/maps3.js" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAz77U5XQuEME6TpftaMdX0bBelQxXRlM&amp;callback=initMap" type="text/javascript"></script>


	@await RenderSectionAsync("Scripts", required: false)
	</body>
	</html>